project_name: gonautobot
release:
  github:
    owner: josh5276
    name: gonautobot
  name_template: '{{.Tag}}'
artifactories:
  - name: production
    mode: archive
    target: https://artifacts.rackspace.net/artifactory/dcm-generic-local/{{ .ProjectName }}/{{ .Tag }}/
    checksum: true
dockers:
  - image_templates:
      - 'dcm-docker-local.artifacts.rackspace.net/dcm/{{ .ProjectName }}:{{ .Tag }}'
    skip_push: false
builds:
- goos:
  - linux
  targets:
  - linux_amd64
  main: api/api.go
  ldflags: -s -w -X main.buildVersion={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -linkmode external -extldflags -static
  binary: discover
  env:
  - CC=x86_64-linux-musl-gcc
  - CXX=x86_64-linux-musl-g++
  - CGO_ENABLED=1
  lang: go
  id: discover_nix
archive:
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    386: i386
    amd64: x86_64
    darwin: Darwin
    linux: Linux
    windows: Windows
  format: tar.gz
  files:
  - LICENSE*
  - README*
  - CHANGELOG*
checksum:
  name_template: checksums.txt
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: build
env_files:
  github_token: ~/.config/goreleaser/github_token
github_urls:
  api: https://github.com/api/v3/
  upload: https://github.com/api/uploads/
  download: https://github.com/
